name: "FUXA by SmartLiving.Rocks"
description: "Easy and Web-based Process Visualization (SCADA/HMI/Dashboard) software - now for Home Assistant"
image: "frangoteam/fuxa"
version: "1.2.4"
url: "https://github.com/SmartLiving-Rocks/FUXA/"
slug: "fuxa-slr"

# ===== Ingress aktivieren =====
ingress: true
ingress_entry: "index.html"
panel:
  sidebar_title: "FUXA"
  sidebar_icon: "mdi:chart-timeline-variant"
  url_path: "fuxa"
# ==============================

environment:
  LOG_LEVEL: "info"
options: {}
schema: {}
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - type: addon_config
    read_only: False
    path: /usr/src/app/FUXA/server/_appdata
  - type: share
    read_only: False
    path: /usr/src/app/FUXA/server/_db
  - type: media
    read_only: False
    path: /usr/src/app/FUXA/server/_images
  - type: share
    read_only: False
    path: /usr/src/app/FUXA/server/_logs
startup: services
ports:
  1881/tcp: 1881
